/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router'
import { Route as rootRoute } from './routes/__root'

const IndexLazyImport = createFileRoute('/')()
const ServicesImport = createFileRoute('/services')()
const ContactImport = createFileRoute('/contact')()
const CaseStudiesImport = createFileRoute('/case-studies')()
const AboutImport = createFileRoute('/about')()

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ServicesRoute = ServicesImport.update({
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const CaseStudiesRoute = CaseStudiesImport.update({
  path: '/case-studies',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByFullPath {
    '/': typeof IndexLazyRoute
    '/about': typeof AboutRoute
    '/case-studies': typeof CaseStudiesRoute
    '/contact': typeof ContactRoute
    '/services': typeof ServicesRoute
  }
  interface FileRoutesByTo {
    '/': typeof IndexLazyRoute
    '/about': typeof AboutRoute
    '/case-studies': typeof CaseStudiesRoute
    '/contact': typeof ContactRoute
    '/services': typeof ServicesRoute
  }
  interface FileRoutesById {
    '/': typeof IndexLazyRoute
    '/about': typeof AboutRoute
    '/case-studies': typeof CaseStudiesRoute
    '/contact': typeof ContactRoute
    '/services': typeof ServicesRoute
  }
}

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutRoute,
  CaseStudiesRoute,
  ContactRoute,
  ServicesRoute,
})